apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: webui-virtualservice
spec:
  hosts:
  - "webui.oss"
  gateways:
  - dashboards-gateway-1
  http:
  - route:
    - destination:
        host: webui-service.language.svc.cluster.local
        port:
          number: 7101