apiVersion: v1
kind: Secret
metadata:
  name: postgres-airflow-secret
type: Opaque 
stringData:
  connection: "postgresql+psycopg2://airflow:airflow@postgres-airflow-service.forwarder.svc.cluster.local:5432/airflow"