apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-airflow-pvc
  labels:
    app: postgres-airflow-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
