apiVersion: v1
kind: Service
metadata: 
  name: chisel-server-service
spec:
  selector:
    app: chisel-server
  ports:
  - name: control
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: l1-rd
    port: 8100
    targetPort: 8100
    protocol: TCP
  - name: l1-rs
    port: 8301
    targetPort: 8301
    protocol: TCP
  - name: l2-rd
    port: 8101
    targetPort: 8101
    protocol: TCP
  - name: l2-rs
    port: 8302
    targetPort: 8302
    protocol: TCP
  - name: l3-rd
    port: 8102
    targetPort: 8102
    protocol: TCP
  - name: l3-rs
    port: 8303
    targetPort: 8303
    protocol: TCP
  - name: c2-rd
    port: 8401
    targetPort: 8401
    protocol: TCP
  - name: c2-rs
    port: 8451
    targetPort: 8451
    protocol: TCP