apiVersion: v1
kind: Service
metadata:
  name: celery-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '7602'
spec:
  selector: 
    app: celery-server
  ports:
    - port: 7602
      targetPort: 7602