apiVersion: v1
kind: Endpoints
metadata:
   name: ray-local-3-client
subsets:
  - addresses:
    - ip: '192.168.1.19'
    ports: 
      - port: 8153
---
apiVersion: v1
kind: Service
metadata:
   name: ray-local-3-client 
spec:
   type: ClusterIP
   ports:
   - protocol: TCP
     port: 8153
     targetPort: 8153
